### ISSUE TITLE
footerni active holatida xatolik bor

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Ansor-med#1]
kutilgan natija:
![image](https://user-images.githubusercontent.com/102718840/163318966-feb5a8da-33ce-4b35-a6ec-d679d5033e72.png)

hozirgi holat:
![image](https://user-images.githubusercontent.com/102718840/163319196-fb80b6c5-7f48-44b2-80cb-c8e3f1ffd4ea.png)

**Comment by Sardor0795** [comment]
I've fixed this problem. Thanks for code review!
