### ISSUE TITLE
Headerdagi logotipda xatolok bor

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Ansor-med#2]
hozirgi holat:
![image](https://user-images.githubusercontent.com/102718840/163321547-8dcd561a-1d6e-40e9-8e72-11b06c7d5bfb.png)

so'ralgan narsa;
logoni jpg formatida olish kerak edi. agar rasmni svg formatida olsek uni 2x varianti shartmas 
class berishda classni turgan positsiyadan kelib chiqib bergan avfzal. shunchaki logo emas balki "header-logo" degan avfzal.

**Comment by Sardor0795** [comment]
@oyatillo0201 Thanks for code review. I've fixed this problem!!!
