### ISSUE TITLE
Mainda

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Ansor-med#3]
ro'yxatga oid shunga o'xshash narsalardi har bittasiga alohida "div"  "p" da bergandan. Hammasini bita "ul" bergan yaxshiroq
![image](https://user-images.githubusercontent.com/102718840/163324035-ad88ca4c-edc5-4a7f-908b-bdc99b6216d6.png)

**Comment by Sardor0795** [comment]
Menga shunisi qulayroq!!!
