### ISSUE TITLE
class berishda

### ISSUE THREAD

**Issue by oyatillo0201** [Sardor0795/Ansor-med#4]
umimiy elementga bita class berib u orqali ichidagi " ul" , "li" yoki "a" chaqirgandan ko'ra. Style berilyakan elentni o'ziga alohida class bergan yaxshi
![image](https://user-images.githubusercontent.com/102718840/163325344-0d370be3-b6dc-4b90-9887-e48d71cbcdcf.png)
![image](https://user-images.githubusercontent.com/102718840/163325499-87b5ec54-c777-49c7-bc56-9a6313c5ae4d.png)

osonroq  varianti:
![image](https://user-images.githubusercontent.com/102718840/163325793-d9962ced-1c7a-4e24-90e0-63eb612b5012.png)
![image](https://user-images.githubusercontent.com/102718840/163326024-7ae8bc4a-db38-4cde-ae3e-c68da981f93a.png)

**Comment by Sardor0795** [comment]
Ha bu to'g'ri!!!

Xammasi to'g'irlandi...


HTML:

![image](https://user-images.githubusercontent.com/87645525/163332115-2263f323-3cde-4b0d-8919-463f57a4ff90.png)
 
CSS:

![image](https://user-images.githubusercontent.com/87645525/163332334-f26b505f-2969-497a-b99d-0ac1d9f4b387.png)

![image](https://user-images.githubusercontent.com/87645525/163332379-60f08a1f-f3cc-4d7c-9677-00e82db08c93.png)
